FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=passwordRoot
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=juanPablo
ENV MYSQL_PASSWORD=Ramire*Pablo

# Exponer el puerto de MySQLx
EXPOSE 3306